=== NMeswania/DnD_App/dnd_app/data/schemas/proficiencies_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "proficiencies_schema",
  "description": "Schema for representing characters proficiencies",
  "type": "object",
  "properties": {
    "armor": {"type":"array", "items": { "type": "string"}},
    "weapons": {"type":"array", "items": { "type": "string"}},
    "tools": {"type":"array", "items": { "type": "string"}},
    "languages": {"type":"array", "items": { "type": "string"}}
  }
}

=== NMeswania/DnD_App/dnd_app/data/character/subs/proficiencies.json
{
  "armor": [
    "light_armor"
  ],
  "weapons": [
    "simple_weapons",
    "hand_crossbows",
    "longswords",
    "rapiers",
    "shortswords"
  ],
  "tools": [
    "lute",
    "triangle",
    "ocarina",
    "navigators_tools",
    "hammock"
  ],
  "languages": [
    "common",
    "elvish",
    "abyssal",
    "draconic"
  ]
}
