=== NMeswania/DnD_App/data/schemas/equipment_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "equipment_schema",
  "description": "Schema for representing equipment information",
  "type": "object",
  "required": [
    "name",
    "equipment_description",
    "rarity"
  ],
  "properties": {
    "name": {
      "description": "Readable name of equipment",
      "type": "string"
    },
    "equipment_description": {
      "description": "Main equipment description",
      "type": "string"
    },
    "rarity": {
      "description": "Rarity of the equipment item(s)",
      "type": "string",
      "enum": [
        "Common",
        "Uncommon",
        "Rare",
        "Very rare",
        "Legendary"
      ]
    },
    "tags": {
      "description": "List of properties for the equipment",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== NMeswania/DnD_App/data/equipment/navigators_tools.json
{
  "name": "Navigators' tools",
  "equipment_description": "This set of instruments is used for Navigation at sea. Proficiency with navigator's tools lets you chart a ship's course and follow Navigation charts. In addition, these tools allow you to add your Proficiency Bonus to any ability check you make to avoid Getting Lost at sea.",
  "rarity": "Common",
  "tags": ["tools"]
}
