=== NMeswania/DnD_App/data/schemas/character/ability_scores_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://json-schema.org/draft-07/schema#",
  "title": "ability_scores_schema",
  "description": "Schema for representing ability scores, saving throws and skills",
  "type": "object",
  "required": [
    "inspiration",
    "proficiency_bonus",
    "ability_scores",
    "saving_throws",
    "skills"
  ],
  "properties": {
    "inspiration": {
      "type": "boolean"
    },
    "proficiency_bonus": {
      "type": "integer"
    },
    "ability_scores": {
      "type": "object",
      "ref": "#/definitions/ability_scores"
    },
    "saving_throws": {
      "type": "object",
      "ref": "#/definitions/saving_throws"
    },
    "skills":{
      "type": "object",
      "ref": "#/definitions/skills"
    }
  },
  "definitions": {
    "ability_scores": {
      "type": "object",
      "required": [
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma"
      ],
      "properties": {
        "strength": { "type": "object", "ref": "#definitions/ability_score" },
        "dexterity": { "type": "object", "ref": "#definitions/ability_score" },
        "constitution": { "type": "object", "ref": "#definitions/ability_score" },
        "intelligence": { "type": "object", "ref": "#definitions/ability_score" },
        "wisdom": { "type": "object", "ref": "#definitions/ability_score" },
        "charisma": { "type": "object", "ref": "#definitions/ability_score" }
      }
    },
    "saving_throws": {
      "type": "object",
      "required": [
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma"
      ],
      "properties": {
        "strength": { "type": "object", "ref": "#definitions/saving_throw" },
        "dexterity": { "type": "object", "ref": "#definitions/saving_throw" },
        "constitution": { "type": "object", "ref": "#definitions/saving_throw" },
        "intelligence": { "type": "object", "ref": "#definitions/saving_throw" },
        "wisdom": { "type": "object", "ref": "#definitions/saving_throw" },
        "charisma": { "type": "object", "ref": "#definitions/saving_throw" }
      }
    },
    "skills": {
      "type": "object",
      "required": [
        "acrobatics",
        "animal_handling",
        "arcana",
        "athletics",
        "deception",
        "history",
        "insight",
        "intimidation",
        "investigation",
        "medicine",
        "nature",
        "perception",
        "performance",
        "persuasion",
        "religion",
        "slight_of_hand",
        "stealth",
        "survival"
      ],
      "properties": {
        "acrobatics": { "type": "object", "ref": "#definitions/skill" },
        "animal_handling": { "type": "object", "ref": "#definitions/skill" },
        "arcana": { "type": "object", "ref": "#definitions/skill" },
        "athletics": { "type": "object", "ref": "#definitions/skill" },
        "deception": { "type": "object", "ref": "#definitions/skill" },
        "history": { "type": "object", "ref": "#definitions/skill" },
        "insight": { "type": "object", "ref": "#definitions/skill" },
        "intimidation": { "type": "object", "ref": "#definitions/skill" },
        "investigation": { "type": "object", "ref": "#definitions/skill" },
        "medicine": { "type": "object", "ref": "#definitions/skill" },
        "nature": { "type": "object", "ref": "#definitions/skill" },
        "perception": { "type": "object", "ref": "#definitions/skill" },
        "performance": { "type": "object", "ref": "#definitions/skill" },
        "persuasion": { "type": "object", "ref": "#definitions/skill" },
        "religion": { "type": "object", "ref": "#definitions/skill" },
        "slight_of_hand": { "type": "object", "ref": "#definitions/skill" },
        "stealth": { "type": "object", "ref": "#definitions/skill" },
        "survival": { "type": "object", "ref": "#definitions/skill" }
      }
    },
    "ability_score": {
      "type": "object",
      "required": [ "modifier", "base_number" ],
      "properties": {
        "modifier": { "type": "integer" },
        "base_number": { "type": "integer" }
      }
    },
    "saving_throw": {
      "type": "object",
      "required": [ "modifier", "proficiency" ],
      "properties": {
        "modifier": { "type": "integer" },
        "proficiency": { "type": "boolean" }
      }
    },
    "skill": {
      "type": "object",
      "required": [ "modifier", "proficiency", "ability" ],
      "properties": {
        "modifier": { "type": "integer" },
        "proficiency": { "type": "boolean" },
        "ability": { "type": "string" }
      }
    }
  }
}

=== NMeswania/DnD_App/data/character/subs/ability_scores.json
{
  "inspiration": true,
  "proficiency_bonus": 3,
  "ability_scores": {
    "strength": { "modifier": 0, "base_number": 10 },
    "dexterity": { "modifier": 3, "base_number": 17 },
    "constitution": { "modifier": 1, "base_number": 12 },
    "intelligence": { "modifier": -2, "base_number": 7 },
    "wisdom": { "modifier": 0, "base_number": 10 },
    "charisma": { "modifier": 5, "base_number": 20 }
  },
  "saving_throws": {
    "strength": { "modifier": 0, "proficiency": false },
    "dexterity": { "modifier": 6, "proficiency": true },
    "constitution": { "modifier": 1, "proficiency": false },
    "intelligence": { "modifier": -1, "proficiency": false },
    "wisdom": { "modifier": 0, "proficiency": false },
    "charisma": { "modifier": 8, "proficiency": true }
  },
  "skills": {
    "acrobatics": { "modifier": 3, "proficiency": false, "ability": "dexterity" },
    "animal_handling": { "modifier": 3, "proficiency": true, "ability": "wisdom" },
    "arcana": { "modifier": -2, "proficiency": false, "ability": "intelligence" },
    "athletics": { "modifier": 0, "proficiency": false, "ability": "strength" },
    "deception": { "modifier": 8, "proficiency": true, "ability": "charisma" },
    "history": { "modifier": -2, "proficiency": false, "ability": "intelligence" },
    "insight": { "modifier": 3, "proficiency": true, "ability": "wisdom" },
    "intimidation": { "modifier": 11, "proficiency": true, "ability": "charisma" },
    "investigation": { "modifier": 1, "proficiency": true, "ability": "intelligence" },
    "medicine": { "modifier": 0, "proficiency": false, "ability": "wisdom" },
    "nature": { "modifier": -2, "proficiency": false, "ability": "intelligence" },
    "perception": { "modifier": 3, "proficiency": true, "ability": "wisdom" },
    "performance": { "modifier": 5, "proficiency": false, "ability": "charisma" },
    "persuasion": { "modifier": 8, "proficiency": true, "ability": "charisma" },
    "religion": { "modifier": -2, "proficiency": false, "ability": "intelligence" },
    "slight_of_hand": { "modifier": 3, "proficiency": false, "ability": "dexterity" },
    "stealth": { "modifier": 6, "proficiency": true, "ability": "dexterity" },
    "survival": { "modifier": 6, "proficiency": true, "ability": "wisdom" }
  }
}
